### ISSUE TITLE
Mac/Linux Version?

### ISSUE THREAD

**Issue by 0xCUB3** [fmhy/dvmob#1]
Is it possible to compile this to work on macOS or GNU/Linux?

**Comment by ggtylerr** [comment]
This is a mobile app, so no. You can build for iOS on Mac *(...which is the only way to make an iOS version)* and you can build for Android on any desktop OS, but you can't make desktop versions.

**Comment by 0xCUB3** [comment]
I see @ggtylerr I was just wondering since there is a Windows version

**Comment by ggtylerr** [comment]
It isn't an actual Windows version. AFAIK It's just the mobile app being run in an emulator. You can't even build an exe.

**Comment by 0xCUB3** [comment]
I see, thanks for the clarification
